---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-logging-openshift-io-v1-clusterlogging
  failurePolicy: Fail
  name: vclusterlogging.logging.openshift.io
  rules:
  - apiGroups:
    - logging.openshift.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterloggings
  sideEffects: None
