//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mechanism) DeepCopyInto(out *Mechanism) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mechanism.
func (in *Mechanism) DeepCopy() *Mechanism {
	if in == nil {
		return nil
	}
	out := new(Mechanism)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Mechanism) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MechanismSpec) DeepCopyInto(out *MechanismSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MechanismSpec.
func (in *MechanismSpec) DeepCopy() *MechanismSpec {
	if in == nil {
		return nil
	}
	out := new(MechanismSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MechanismStatus) DeepCopyInto(out *MechanismStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MechanismStatus.
func (in *MechanismStatus) DeepCopy() *MechanismStatus {
	if in == nil {
		return nil
	}
	out := new(MechanismStatus)
	in.DeepCopyInto(out)
	return out
}
